### ISSUE TITLE
Request redirect

### ISSUE THREAD

**Issue by wolfthefallen** [securestate/king-phisher-plugins#40]
when setting up the server Request Redirect plugin I get the following stack trace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/king-phisher/king_phisher/server/__main__.py", line 277, in <module>
    sys.exit(main())
  File "/opt/king-phisher/king_phisher/server/__main__.py", line 271, in main
    status_code = build_and_run(arguments, config, plugin_manager, log_file)
  File "/opt/king-phisher/king_phisher/server/__main__.py", line 78, in build_and_run
    king_phisher_server = build.server_from_config(config, plugin_manager=plugin_manager)
  File "/opt/king-phisher/king_phisher/server/build.py", line 186, in server_from_config
    signals.server_initialized.send(server)
  File "/opt/king-phisher/.venv/lib/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/opt/king-phisher/.venv/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/opt/king-phisher-plugins/server/request_redirect.py", line 203, in on_server_initialized
    self.entries.append(self._entry_from_raw(entry, idx))
  File "/opt/king-phisher-plugins/server/request_redirect.py", line 102, in _entry_from_raw
    entry = entry.copy()
AttributeError: 'str' object has no attribute 'copy'
```

the entry is coming in as a string of `rules`.

server_config.yml plugin settings:
```
  # Add additional search paths for plugin directories
  plugin_directories:
    - /opt/king-phisher-plugins/server
  # Auto install server plugin Python requirements
  plugin_install_requirements: true
  # Library path for plugin dependencies
  plugin_library_path: /var/king-phisher/lib
  # List the plugins that need to be enabled
  plugins:
  #The plugin to enable's name
    request_redirect:
      entries:
        rules:
          - source: 0.0.0.0/0
            target: "https://www.google.com"
```

**Comment by zeroSteiner** [comment]
Alright so versions of the plugin before 2.0 used "rules" as the collection but with version 2.0 this changed to "entries".

You just need to change your config to:

```
request_redirect:
  entries:
    - source: 0.0.0.0/0
      target: "https://www.google.com"
```

That should do the trick, sorry for the confusion.
